config/routes.rb
Rails.application.routes.draw do

  resources :vehicles

end

app/models/vehicle.rb
class Vehicle < ActiveRecord::Base
  
  # SEARCH VEHICLES
  def self.search(search)             
    Vehicle.where("lower(year || ' ' || make || ' ' || model) LIKE ?", "%#{search.downcase}%")
  end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/vehicles_controller.rb
class VehiclesController < ApplicationController
  def index
    if params[:search]
      @vehicles = Vehicle.search(params[:search]).paginate(:page => params[:page], :per_page => 50)
    else
      @vehicles = Vehicle.all.paginate(:page => params[:page], :per_page => 50)
    end
  end

  def new
    @vehicle = Vehicle.new
  end

  def create
    @vehicle = Vehicle.build(vehicle_params)    

    if @vehicle.save
      flash[:notice] = "Vehicle was saved."
      redirect_to vehicle_path
    else
      flash[:error] = "There was an error saving the vehicle. Please try again."
      render :new
    end
  end

  def edit
    @vehicle = Vehicle.find(params[:id])
  end

  def update
    @vehicle = Vehicle.find(params[:id])    

    if @vehicle.save
      flash[:notice] = "Vehicle was saved."
      redirect_to vehicle_path
    else
      flash[:error] = "There was an error saving the vehicle. Please try again."
      render :new
    end    
  end

  def destroy
    @vehicle = Vehicle.find(params[:id])    

    if @vehicle.destroy
      flash[:notice] = "Vehicle  was deleted successfully."
      redirect_to @vehicle
    else
      flash[:error] = "There was an error deleting the vehicle. Please try again."
      render :show
    end
  end

  def show
    @vehicle.find(params[:id])
  end

  private

  def vehicle_params
    params.require(:vehicle).permit(:year, :make, :model)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/vehicles_helper.rb
module VehiclesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Carlist</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/vehicles/edit.html.erb
<h1>Vehicles#edit</h1>
<p>Find me in app/views/vehicles/edit.html.erb</p>

app/views/vehicles/index.html.erb
<h1>Vehicles#index</h1>
<label>Vehicle Search</label>
<%= form_tag(vehicles_path, :method => "get", id: "search-form") do %>
  <%= text_field_tag :search, params[:search].to_s, placeholder: "Search Vehicles" %>
  <%= submit_tag "Search" %>
<% end %>

<% if @vehicles.present? %>
  <table>
    <tr>
      <td>Year:</td>
      <td>Model:</td>
      <td>Make:</td>
      <td>Edit:</td>
      <td>Destroy:</td>
    </tr>
  <% @vehicles.each do |vehicle| %>
    <tr>
      <td>
        <%= vehicle.year %>
      </td>
      <td>
        <%= vehicle.make %>
      </td>
      <td>
        <%= vehicle.model %>
      </td>
      <td>
        <%= link_to 'Edit', edit_vehicle_path(vehicle) %>
      </td>
      <td>
        <%= link_to 'Delete', vehicle, method: :delete, data: {confirm: "Do you really want to delete the vehicle: #{vehicle.year} #{vehicle.make} #{vehicle.model}"}, :class => 'remove-btn' %>
      </td>
    </tr>
  <% end %>
  </table>
  <%= will_paginate @vehicles %>
<% else %>
  <p>Nothing found with the term(s) "<%= params[:search] %>".</p>
<% end %>

app/views/vehicles/new.html.erb
<h1>Vehicles#new</h1>
<p>Find me in app/views/vehicles/new.html.erb</p>

app/views/vehicles/show.html.erb
<h1>Vehicles#show</h1>
<p>Find me in app/views/vehicles/show.html.erb</p>